name: Deploy Flask Backend

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Upgrade setuptools and wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel


    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libopenblas-dev liblapack-dev libx11-dev libgtk-3-dev
        sudo apt-get install -y python3-dev python3-pip python3-venv build-essential

    - name: Install dependencies
      run: |
        cd Python-api
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Flask Backend
      run: |
        cd Python-api
        zip -r api.zip .  # Zip the Flask app
        az webapp deployment source config-zip --resource-group AttendanceManagement --name ASP-AttendanceManagement-8afb --src api.zip
