name: Deploy Flask Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Upgrade setuptools and wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Upgrade CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenblas-dev libx11-dev g++ build-essential

    - name: Pin pybind11 to compatible version
      run: |
        pip install pybind11==2.10.0

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('Python-api/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        cd Python-api
        pip install -r requirements.txt
        pip install dlib==19.22.99 --no-cache-dir

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Flask Backend
      run: |
        cd Python-api
        zip -r api.zip .  # Zip the Flask app
        az webapp deployment source config-zip --resource-group AttendanceManagement --name ASP-AttendanceManagement-8afb --src api.zip
